sudo: false

language: go
go:
  - 1.9

install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go build .
  - ./test.sh
  - mkdir -p reports
  - go test -v -coverprofile=reports/coverage-flagset.coverprofile -covermode=count github.com/devfacet/gocmd/flagset
  - go test -v -coverprofile=reports/coverage-table.coverprofile -covermode=count github.com/devfacet/gocmd/table
  - go test -v -coverprofile=reports/coverage-template.coverprofile -covermode=count github.com/devfacet/gocmd/template
  - go test -v -coverprofile=reports/coverage-main.coverprofile -covermode=count github.com/devfacet/gocmd
  - gover reports/ reports/coverage-all.coverprofile
  - go tool cover -func=reports/coverage-all.coverprofile
  - goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN -covermode=count -coverprofile=reports/coverage-all.coverprofile
